### ISSUE TITLE
Last value always missing for the posterior probability distribution

### ISSUE THREAD

**Issue by emilyhalford** [swang87/bcp#3]
I am using the bcp package for change point detection and am wondering why the last value of the probability distribution is always "NA". I'm wondering if perhaps the bcp algorithm requires a data point after a particular date in order to provide a value or if this is a bug. My study period ends the week of 12-29-2019, and I'm wondering whether or not I need an additional week of data in order to truly capture a study period through the week of 12-29-2019.

I have been unable to find an explanation in the package documentation and any explanation would be greatly appreciated. This has happened any time that I use the bcp function, but I'm including a reproducible example below:

Packages:

`library(gtrendsR)`
`library(tidyverse)`
`library(bcp)`

Pulling sample Google Trends data:

`data = gtrends('stackoverflow', geo = "US-OR", time = "2018-04-01 2019-12-31")$interest_over_time %>% 
  select(-time:-category)`

Using bcp package:

`bcp = bcp(data$hits)`
  
`prob = bcp$posterior.prob`
`prob = as.data.frame(prob)`

`bcp_dataframe = cbind(data, prob) %>% 
    select(date, prob)`

Resulting dataframe:
![image](https://user-images.githubusercontent.com/54901666/97710453-25ffca80-1a92-11eb-89ff-52d01edb5519.png)

**Comment by swang87** [comment]
Hi Emily,

Thanks for your note. The last value by the definition of our model is always the end of a block, so we don't actually estimate a posterior probability for that position by design. Let me know if this doesn't make sense.

**Comment by emilyhalford** [comment]
Thank you for the clarification!
