### ISSUE TITLE
bcp has been removed from CRAN

### ISSUE THREAD

**Issue by mkoohafkan** [swang87/bcp#6]
Is this package still being maintained?

https://cran.r-project.org/package=bcp

**Comment by atkissoncj** [comment]
As far as I can tell, it is not. It hasn't received any updates in 6 years. It was removed from CRAN for mail undeliverable. Presumably, the organizational account of the person who developed it was disconnected.

Also as far as I can tell, it still works just fine. Nothing is stale, the math hasn't changed, all should work as normal. I currently use it in projects. You just have to install it from github.

**Comment by swang87** [comment]
This package hasn't been updated for 6 years and has been removed from CRAN due to neglect on my part, but @jayemerson is looking to revive it!

**Comment by jayemerson** [comment]
Still have this on my list.  !-)  Have fun today!  I have to pass, trying
to squeeze in lunch with a practice job talk for one of our 5th-year
students.  !-)

Jay

John W. Emerson (Jay, he/him/his)
Professor of Statistics (Adjunct) and Director of Graduate Studies
Department of Statistics and Data Science
Yale University
http://www.stat.yale.edu/~jay
